# Basic parameters
seed: 1234  # e.g, 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Data (csv) files
data_folder: !PLACEHOLDER #../../../../samples/voxceleb_samples/wav/
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv

# Training hyperparameters
number_of_epochs: 10
batch_size: 6
lr: 0.002
device: 'cpu'

# Feature parameters
n_mels: 24
left_frames: 0
right_frames: 0
deltas: False

# Number of speakers
out_n_neurons: 2

# Functions
compute_features: !new:speechbrain.lobes.features.fbank.Fbank
    n_mels: !ref <n_mels>
    left_frames: !ref <left_frames>
    right_frames: !ref <right_frames>
    deltas: !ref <deltas>

model: !new:speechbrain.lobes.models.Xvector.Xvector
    activation: !name:torch.nn.LeakyReLU
    device: !ref <device>
    tdnn_blocks: 5
    tdnn_channels: 512
    tdnn_kernel_sizes: [5, 3, 3, 1, 1]
    tdnn_dilations: [1, 2, 3, 1, 1]
    tdnn_fin_channels: 1500
    lin_blocks: 2
    lin_neurons: 512


train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <batch_size>
    csv_read: [wav, spk_id]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <batch_size>
    csv_read: [wav, spk_id]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

out_linear: !new:speechbrain.nnet.linear.Linear
    n_neurons: !ref <out_n_neurons>
    bias: True

softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

compute_cost: !name:speechbrain.nnet.losses.nll_loss

compute_error: !name:speechbrain.nnet.losses.classification_error

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
    learning_rate: !ref <lr>
