# Basic parameters
output_folder: results/minimal/nmf_sourcesep
sample_rate: 16000

# Data files
data_folder: ../../../../samples/audio_samples/sourcesep_samples
csv_train: !ref <data_folder>/csv_example_sourcesep_source1.csv
csv_train2: !ref <data_folder>/csv_example_sourcesep_source2.csv
csv_test: !ref <data_folder>/csv_example_sourcesep_mixture.csv

# NMF parameters
N_epochs: 500
K: 20 # this specifies the number of template vectors to use in NMF.
N_batch: 200
m: 513  # length of stft vectors
win_length: 40  # window length (in ms) for stft
hop_length: 10  # hop length (in ms) for stft

# Experiment flags:
save_reconstructed: True   # saves the results
copy_original_files: True    # copies the original files

train_loader1: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <N_batch>
    csv_read: [wav]
    output_folder: !ref <output_folder>
    sentence_sorting: 'original'
    replacements:
        $data_folder: !ref <data_folder>

train_loader2: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train2>
    batch_size: !ref <N_batch>
    csv_read: [wav]
    output_folder: !ref <output_folder>
    sentence_sorting: 'original'
    replacements:
        $data_folder: !ref <data_folder>

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    batch_size: !ref <N_batch>
    csv_read: [wav]
    sentence_sorting: 'original'
    output_folder: !ref <output_folder>
    replacements:
        $data_folder: !ref <data_folder>

compute_features: !new:speechbrain.processing.features.STFT
    sample_rate: !ref <sample_rate>
    n_fft: 1024
    win_length: !ref <win_length>
    hop_length: !ref <hop_length>
