repos:
    - repo: local
      hooks:
          - id: linters
            name: linters
            entry: ./.run-linters.sh
            language: script
            pass_filenames: False
            always_run: True
            require_serial: False

          - id: unittests
            name: unittests
            entry: ./.run-unittests.sh
            language: script
            pass_filenames: False
            always_run: True
            require_serial: False

          - id: doctests
            name: doctests
            entry: ./.run-doctests.sh
            language: script
            pass_filenames: False
            always_run: True
            require_serial: False
