# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Data files
data_folder: !PLACEHOLDER
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv

# Neural Parameters
N_epochs: 25
N_batch: 2
lr: 0.0004

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <N_batch>
    csv_read: [wav, ali]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <N_batch>
    csv_read: [wav, ali]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    csv_read: [wav, ali]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

compute_features: !new:speechbrain.lobes.features.mfcc.MFCC

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

linear1: !new:speechbrain.nnet.linear.Linear
    n_neurons: 1024
    bias: False

activation: !new:torch.nn.LeakyReLU

linear2: !new:speechbrain.nnet.linear.Linear
    n_neurons: 43
    bias: False

softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

compute_cost: !name:speechbrain.nnet.losses.nll_loss

compute_error: !name:speechbrain.nnet.losses.classification_error

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
    learning_rate: !ref <lr>
