# Seed needs to be set at top of yaml, before objects with parameters are made
# NOTE: Seed does not guarantee replicability with CTC
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Data files
data_folder: !PLACEHOLDER
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv

# Neural Parameters
N_epochs: 50
N_batch: 1
lr: 0.008

# Model parameters
activation: !name:torch.nn.LeakyReLU []

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <N_batch>
    csv_read: [wav, phn]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <N_batch>
    csv_read: [wav, phn]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    csv_read: [wav, phn]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

compute_features: !new:speechbrain.lobes.features.mfcc.MFCC

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

conv1: !new:speechbrain.nnet.complex_networks.CNN.ComplexConv1d
    out_channels: 16
    kernel_size: 3

cln1: !new:speechbrain.nnet.complex_networks.normalization.ComplexLayerNorm

conv2: !new:speechbrain.nnet.complex_networks.CNN.ComplexConv1d
    out_channels: 32
    kernel_size: 3

cln2: !new:speechbrain.nnet.complex_networks.normalization.ComplexLayerNorm

pooling: !new:speechbrain.nnet.pooling.Pooling1d
    pool_type: "avg"
    kernel_size: 3

rnn: !new:speechbrain.nnet.complex_networks.RNN.ComplexLiGRU
    hidden_size: 64
    bidirectional: True

lin: !new:speechbrain.nnet.linear.Linear
    n_neurons: 43  # 42 phonemes + 1 blank
    bias: False

softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

compute_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: 42

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
    learning_rate: !ref <lr>
