# ################################
# Model: 1-D causal CNNTransformer model
# Authors: Chien-Feng Liao
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234  # e.g, 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

data_folder: !PLACEHOLDER
test_clean_folder: !ref <data_folder>/clean_testset_wav_16k/

output_folder: \
    !ref ./results/semicausal_modularTransformer_comp_16head/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
enhanced_folder: !ref <output_folder>/enhanced

# Basic parameters
use_tensorboard: False
tensorboard_logs: \
    !ref ./results/semicausal_modularTransformer_comp_16head/<seed>/logs/

# FFT paremeters
Sample_rate: 16000
Win_length: 32
Hop_length: 16
N_fft: 512

# Data files
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/test.csv
csv_test: !ref <data_folder>/test.csv

# Training Parameters
number_of_epochs: 50
N_batch: 16
lr: 0.0002
device: 'cuda:0'

# Model Parameters
dropout: 0.1
num_blocks: 8
intermediate_size: 512
nhead: 16
causal: True
kernel_size: 3
base_channels: 1024
padding_type: causal
num_modules: 2
group_comm: True

activation: !name:torch.nn.LeakyReLU
output_activation: !name:torch.nn.ReLU
CNN_activation: !new:torch.nn.LeakyReLU

conv1: !new:speechbrain.nnet.CNN.Conv1d
    out_channels: !ref <base_channels>
    kernel_size: !ref <kernel_size>
    padding: !ref <padding_type>

conv2: !new:speechbrain.nnet.CNN.Conv1d
    out_channels: !ref <base_channels> // 2
    kernel_size: !ref <kernel_size>
    padding: !ref <padding_type>

conv3: !new:speechbrain.nnet.CNN.Conv1d
    out_channels: !ref <base_channels> // 8
    kernel_size: !ref <kernel_size>
    padding: !ref <padding_type>

conv4: !new:speechbrain.nnet.CNN.Conv1d
    out_channels: !ref <base_channels> // 4
    kernel_size: !ref <kernel_size>
    padding: !ref <padding_type>

layernorm1: !new:speechbrain.nnet.normalization.LayerNorm
layernorm2: !new:speechbrain.nnet.normalization.LayerNorm
layernorm3: !new:speechbrain.nnet.normalization.LayerNorm
layernorm4: !new:speechbrain.nnet.normalization.LayerNorm

CNN: !new:speechbrain.nnet.containers.Sequential
    - !ref <conv1>
    - !ref <layernorm1>
    - !ref <CNN_activation>
    - !ref <conv2>
    - !ref <layernorm2>
    - !ref <CNN_activation>
    - !ref <conv3>
    - !ref <layernorm3>
    - !ref <CNN_activation>
    - !ref <conv4>
    - !ref <layernorm4>
    - !ref <CNN_activation>

model: !new:speechbrain.lobes.models.transformer.TransformerSE.CNNTransformerSE
    output_size: !ref <N_fft> // 2 + 1
    output_activation: !ref <output_activation>
    activation: !ref <activation>
    causal: !ref <causal>
    num_layers: !ref <num_blocks>
    d_ffn: !ref <intermediate_size>
    nhead: !ref <nhead>
    dropout: !ref <dropout>
    custom_emb_module: !ref <CNN>
    num_modules: !ref <num_modules>
    use_group_comm: !ref <group_comm>

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <N_batch>
    csv_read: [noisy_wav, clean_wav]
    sentence_sorting: ascending
    output_folder: !ref <output_folder>

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <N_batch>
    csv_read: [noisy_wav, clean_wav]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    batch_size: !ref <N_batch>
    csv_read: [noisy_wav, clean_wav]
    replacements:
        $data_folder: !ref <data_folder>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
    summary_fns:
        loss: !name:speechbrain.utils.train_logger.summarize_average

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

compute_STFT: !new:speechbrain.processing.features.STFT
    sample_rate: !ref <Sample_rate>
    win_length: !ref <Win_length>
    hop_length: !ref <Hop_length>
    n_fft: !ref <N_fft>

compute_ISTFT: !new:speechbrain.processing.features.ISTFT
    sample_rate: !ref <Sample_rate>
    win_length: !ref <Win_length>
    hop_length: !ref <Hop_length>

compute_cost: !name:speechbrain.nnet.losses.mse_loss

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
    learning_rate: !ref <lr>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        optimizer: !ref <optimizer>
        counter: !ref <epoch_counter>
