# ################################
# Model: X-vector model for speaker recognition
# Authors: Nauman Dawalatabad & Mirco Ravanelli 2020
# ################################

seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Folders and train_log file
data_folder: /localscratch/voxceleb2
output_folder: results/voxceleb2/verification_discriminator_xvectors
save_folder: !ref <output_folder>/save/
train_log: !ref <output_folder>/train_log.txt

# csv files
csv_train: !ref <save_folder>/train.csv
csv_valid: !ref <save_folder>/dev.csv
csv_enrol: !ref <save_folder>/enrol.csv
csv_test: !ref <save_folder>/test.csv

# Training hyperparameters
number_of_epochs: 25
batch_size: 128
lr: 0.0002500
lr_final: 0.00005000
device: 'cuda:0'
freeze_embeddings: False

# Pretrain from web (as an alternative specify a file)
pretrain_embeddings: True
embedding_file:
    https://www.dropbox.com/s/p51au63q72jabqf/xvector_model.ckpt?dl=1

# Feature parameters
n_mels: 24
left_frames: 0
right_frames: 0
deltas: False

# Number of speakers
out_n_neurons: 1211

# Functions
compute_features: !new:speechbrain.lobes.features.fbank.Fbank
    n_mels: !ref <n_mels>
    left_frames: !ref <left_frames>
    right_frames: !ref <right_frames>
    deltas: !ref <deltas>

embedding_model: !new:speechbrain.lobes.models.Xvector.Xvector
    activation: !name:torch.nn.LeakyReLU
    device: !ref <device>
    tdnn_blocks: 5
    tdnn_channels: [512, 512, 512, 512, 1500]
    tdnn_kernel_sizes: [5, 3, 3, 1, 1]
    tdnn_dilations: [1, 2, 3, 1, 1]
    lin_neurons: 512

discriminator: !new:speechbrain.lobes.models.Xvector.Discriminator
    activation: !name:torch.nn.LeakyReLU
    device: !ref <device>
    lin_blocks: 1
    lin_neurons: 4096
    out_neurons: 1

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

env_corrupt: !new:speechbrain.lobes.augment.env_corrupt.EnvCorrupt
    openrir_folder: !ref <data_folder>
    openrir_max_noise_len: 3.0  # seconds
    reverb_prob: 1.0
    noise_prob: 1.0
    noise_snr_low: 0
    noise_snr_high: 15
    rir_scale_factor: 1.0

augmentation: !new:speechbrain.lobes.augment.tdsa.TimeDomainSpecAugment
    sample_rate: 16000
    speeds: [100]

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <batch_size>
    csv_read: [wav, spk_id]
    sentence_sorting: random
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <batch_size>
    csv_read: [wav, spk_id]
    sentence_sorting: random
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/

enrol_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_enrol>
    batch_size: 1
    csv_read: [wav]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    batch_size: 1
    csv_read: [wav]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

bn_emb: !new:speechbrain.nnet.normalization.BatchNorm1d

compute_cost: !name:speechbrain.nnet.losses.compute_masked_loss

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
    learning_rate: !ref <lr>

lr_annealing: !new:speechbrain.nnet.lr_schedulers.LinearLRScheduler
    lr_initial: !ref <lr>
    lr_final: !ref <lr_final>
    N_epochs: !ref <number_of_epochs>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        embedding_model: !ref <embedding_model>
        discriminator: !ref <discriminator>
        optimizer: !ref <optimizer>
        normalizer: !ref <mean_var_norm>
        counter: !ref <epoch_counter>
        mean_var_norm_emb: !ref <bn_emb>
