# ################################
# Model: ResNet model for speaker recognition
# Authors: Nauman Dawalatabad & Mirco Ravanelli & Hwidong Na 2020
# ################################

seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Folders and train_log file
voxceleb_source: /network/datasets/restricted/voxceleb_users/voxceleb/voxceleb1
data_folder: voxceleb1
output_folder: results/speech-resnet-34-ml
save_folder: !ref <output_folder>/save/
train_log: !ref <output_folder>/train_log.txt

# csv files
csv_train: !ref <save_folder>/train.csv
csv_valid: !ref <save_folder>/dev.csv

# Training hyperparameters
number_of_epochs: 100
batch_size: 512 # 256-way
group_size: 4   # support_size + query_size
query_size: 3
lr: 0.001
lr_final: 0.0001
device: 'cuda:0'

# Evaluation hyperparameters
eval_batch_size: 128 # 64-way
eval_query_size: 1
eval_group_size: 2

# Feature parameters
n_mels: 40
left_frames: 0
right_frames: 0
deltas: False

# Functions
compute_features: !new:speechbrain.lobes.features.fbank.Fbank
    n_mels: !ref <n_mels>
    left_frames: !ref <left_frames>
    right_frames: !ref <right_frames>
    deltas: !ref <deltas>

resnet_model: !new:speechbrain.lobes.models.SpeechResNet.ResNet34
    device: !ref <device>
    in_channels: 1
    lin_neurons: 512

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

env_corrupt: !new:speechbrain.lobes.augment.env_corrupt.EnvCorrupt
    openrir_source: /miniscratch/voxceleb1/rirs_noises.zip
    openrir_folder: !ref <data_folder>
    openrir_max_noise_len: 3.0  # seconds
    reverb_prob: 1.0
    noise_prob: 1.0
    noise_snr_low: 0
    noise_snr_high: 15
    rir_scale_factor: 1.0

augmentation: !new:speechbrain.lobes.augment.tdsa.TimeDomainSpecAugment
    sample_rate: 16000
    speeds: [100]

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <batch_size>
    group_size: !ref <group_size>
    csv_read: [wav, spk_id]
    key_entry: spk_id
    sentence_sorting: groupwise
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <eval_batch_size>
    group_size: !ref <eval_group_size>
    csv_read: [wav, spk_id]
    key_entry: spk_id
    sentence_sorting: groupwise
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/

input_norm: !new:speechbrain.nnet.normalization.InstanceNorm1d

output_norm: !new:speechbrain.nnet.normalization.LpNorm

meta_loss: !new:speechbrain.nnet.losses.ScaledCosineSimiarity
    device: !ref <device>

meta_wrapper: !new:speechbrain.nnet.losses.ProtoNetWrapper
    meta_loss: !ref <meta_loss>

compute_cost: !name:speechbrain.nnet.losses.nll_loss

compute_error: !name:speechbrain.nnet.losses.classification_error

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
    learning_rate: !ref <lr>

lr_annealing: !new:speechbrain.nnet.lr_schedulers.LinearLRScheduler
    lr_initial: !ref <lr>
    lr_final: !ref <lr_final>
    N_epochs: !ref <number_of_epochs>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        resnet_model: !ref <resnet_model>
        meta_loss: !ref <meta_loss>
        optimizer: !ref <optimizer>
        input_norm: !ref <input_norm>
        output_norm: !ref <output_norm>
        counter: !ref <epoch_counter>
