# ################################
# Model: 1-D causal CNNTransformer model with log1p mapping
# Authors: Chien-Feng Liao
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Basic parameters
data_folder: !PLACEHOLDER
output_folder: !ref results/causal_modularTransformer/<seed>
enhanced_folder: !ref <output_folder>/enhanced/

use_tensorboard: False
tensorboard_logs: !ref results/logs/causal_modularTransformer/<seed>
train_log: !ref <output_folder>/train_log.txt

# Data files
csv_noise: !ref <data_folder>/tr_noise.csv
csv_clean: !ref <data_folder>/tr_clean.csv
csv_valid: !ref <data_folder>/valid.csv
csv_test: !ref <data_folder>/test.csv

# Training Parameters
N_epochs: 50
N_batch: 16
lr: 0.0001
device: cuda:0

# Model Parameters
dropout: 0.1
num_blocks: 8
intermediate_size: 512
nhead: 8
causal: True
kernel_size: 3
base_channels: 1024
padding_type: causal
num_modules: 2

# FFT Parameters
samplerate: 16000
n_fft: 512
win_length: 32
hop_length: 16

activation: !name:torch.nn.LeakyReLU
output_activation: !name:torch.nn.ReLU
CNN_activation: !new:torch.nn.LeakyReLU

conv1: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: !ref <base_channels>
  kernel_size: !ref <kernel_size>
  padding: !ref <padding_type>

conv2: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: !ref <base_channels> // 2
  kernel_size: !ref <kernel_size>
  padding: !ref <padding_type>

conv3: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: !ref <base_channels> // 8
  kernel_size: !ref <kernel_size>
  padding: !ref <padding_type>

conv4: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: !ref <base_channels> // 4
  kernel_size: !ref <kernel_size>
  padding: !ref <padding_type>

layernorm1: !new:speechbrain.nnet.normalization.LayerNorm
layernorm2: !new:speechbrain.nnet.normalization.LayerNorm
layernorm3: !new:speechbrain.nnet.normalization.LayerNorm
layernorm4: !new:speechbrain.nnet.normalization.LayerNorm

CNN: !new:speechbrain.nnet.containers.Sequential
  - !ref <conv1>
  - !ref <layernorm1>
  - !ref <CNN_activation>
  - !ref <conv2>
  - !ref <layernorm2>
  - !ref <CNN_activation>
  - !ref <conv3>
  - !ref <layernorm3>
  - !ref <CNN_activation>
  - !ref <conv4>
  - !ref <layernorm4>
  - !ref <CNN_activation>

model: !new:speechbrain.lobes.models.transformer.TransformerSE.CNNTransformerSE
  output_size: !ref <n_fft> // 2 + 1
  output_activation: !ref <output_activation>
  activation: !ref <activation>
  causal: !ref <causal>
  num_layers: !ref <num_blocks>
  d_ffn: !ref <intermediate_size>
  nhead: !ref <nhead>
  dropout: !ref <dropout>
  custom_emb_module: !ref <CNN>
  num_modules: !ref <num_modules>
  use_group_comm: True

add_noise: !new:speechbrain.processing.speech_augmentation.AddNoise
  csv_file: !ref <csv_noise>
  snr_low: 0
  snr_high: 40
  pad_noise: False
  start_index: 0
  csv_read: [wav]

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
  csv_file: !ref <csv_clean>
  batch_size: !ref <N_batch>
  csv_read: [wav]
  cache: False
  num_workers: 1

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
  csv_file: !ref <csv_valid>
  batch_size: !ref <N_batch>
  csv_read: [wav, target]

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
  csv_file: !ref <csv_test>
  batch_size: !ref <N_batch>
  csv_read: [wav, target]

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
  limit: !ref <N_epochs>

compute_stft: !new:speechbrain.processing.features.STFT
  sample_rate: !ref <samplerate>
  win_length: !ref <win_length>
  hop_length: !ref <hop_length>
  n_fft: !ref <n_fft>

compute_istft: !new:speechbrain.processing.features.ISTFT
  sample_rate: !ref <samplerate>
  win_length: !ref <win_length>
  hop_length: !ref <hop_length>

compute_cost: !name:speechbrain.nnet.losses.mse_loss

lr_annealing: !new:speechbrain.nnet.lr_schedulers.NewBobLRScheduler
  improvement_threshold: 0.0
  annealing_factor: 0.5
  patient: 5

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
  learning_rate: !ref <lr>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: !ref <output_folder>/save
  recoverables:
    optimizer: !ref <optimizer>
    counter: !ref <epoch_counter>
    model: !ref <model>
    scheduler: !ref <lr_annealing>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: !ref <train_log>
  summary_fns:
    PESQ: !name:speechbrain.utils.train_logger.summarize_average
    STOI: !name:speechbrain.utils.train_logger.summarize_average
