# ################################
# Model: Baseline 1-D CNN model with log1p mapping
# Authors: Chien-Feng Liao
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: !PLACEHOLDER  # e.g, 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Basic parameters
data_folder: !PLACEHOLDER
output_folder: !ref results/causalCNN_log1p_dynamic/<seed>
enhanced_folder: !ref <output_folder>/enhanced/

use_tensorboard: True
tensorboard_logs: !ref results/logs/causalCNN_log1p_dynamic/<seed>
train_log: !ref <output_folder>/train_log.txt

# Data files
csv_noise: !ref <data_folder>/tr_noise.csv
csv_clean: !ref <data_folder>/tr_clean.csv
csv_valid: !ref <data_folder>/valid.csv
csv_test: !ref <data_folder>/test.csv

# Training Parameters
N_epochs: 50
N_batch: 8
lr: 0.0002
device: cuda:0

# Model Parameters
kernel_size: 7
base_channels: 2048
padding_type: causal

# FFT Parameters
samplerate: 16000
n_fft: 512
win_length: 32
hop_length: 16

add_noise: !new:speechbrain.processing.speech_augmentation.AddNoise
  csv_file: !ref <csv_noise>
  snr_low: 0
  snr_high: 40
  pad_noise: False
  start_index: 0
  csv_read: [wav]

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
  csv_file: !ref <csv_clean>
  batch_size: !ref <N_batch>
  csv_read: [wav]
  cache: False
  num_workers: 1

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
  csv_file: !ref <csv_valid>
  batch_size: !ref <N_batch>
  csv_read: [wav, target]

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
  csv_file: !ref <csv_test>
  batch_size: !ref <N_batch>
  csv_read: [wav, target]

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
  limit: !ref <N_epochs>

compute_stft: !new:speechbrain.processing.features.STFT
  sample_rate: !ref <samplerate>
  win_length: !ref <win_length>
  hop_length: !ref <hop_length>
  n_fft: !ref <n_fft>

compute_istft: !new:speechbrain.processing.features.ISTFT
  sample_rate: !ref <samplerate>
  win_length: !ref <win_length>
  hop_length: !ref <hop_length>

conv1: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: !ref <base_channels>
  kernel_size: !ref <kernel_size>
  padding: !ref <padding_type>

conv2: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: !ref <base_channels> // 2
  kernel_size: !ref <kernel_size>
  padding: !ref <padding_type>

conv3: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: !ref <base_channels> // 4
  kernel_size: !ref <kernel_size>
  padding: !ref <padding_type>

conv4: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: !ref <base_channels> // 8
  kernel_size: !ref <kernel_size>
  padding: !ref <padding_type>

conv5: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: !ref <base_channels> // 16
  kernel_size: !ref <kernel_size>
  padding: !ref <padding_type>

conv6: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: !ref <base_channels> // 8
  kernel_size: !ref <kernel_size>
  padding: !ref <padding_type>

conv7: !new:speechbrain.nnet.CNN.Conv1d
  out_channels: !ref <base_channels> // 4
  kernel_size: !ref <kernel_size>
  padding: !ref <padding_type>

linear: !new:speechbrain.nnet.linear.Linear
  n_neurons: !ref <n_fft> // 2 + 1
  bias: False

activation: !new:torch.nn.LeakyReLU
output_activation: !new:torch.nn.ReLU

model: !new:speechbrain.nnet.containers.Sequential
  - !ref <conv1>
  - !ref <activation>
  - !ref <conv2>
  - !ref <activation>
  - !ref <conv3>
  - !ref <activation>
  - !ref <conv4>
  - !ref <activation>
  - !ref <conv5>
  - !ref <activation>
  - !ref <conv6>
  - !ref <activation>
  - !ref <conv7>
  - !ref <activation>
  - !ref <linear>
  - !ref <output_activation>

compute_cost: !name:speechbrain.nnet.losses.mse_loss

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
  learning_rate: !ref <lr>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: !ref <output_folder>/save
  recoverables:
    optimizer: !ref <optimizer>
    counter: !ref <epoch_counter>
    model: !ref <model>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: !ref <train_log>
  summary_fns:
    PESQ: !name:speechbrain.utils.train_logger.summarize_average
    STOI: !name:speechbrain.utils.train_logger.summarize_average
