# ################################
# Model: X-vector model for speaker recognition
# Authors: Nauman Dawalatabad & Mirco Ravanelli 2020
# ################################

seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Folders and train_log file
voxceleb_source: /network/datasets/restricted/voxceleb_users/voxceleb/voxceleb1
data_folder: /localscratch/voxceleb1
output_folder: results/xvector-clbj
save_folder: !ref <output_folder>/save/
train_log: !ref <output_folder>/train_log.txt

# csv files
csv_train: !ref <save_folder>/train.csv
csv_valid: !ref <save_folder>/dev.csv
csv_test: !ref <save_folder>/test.csv
csv_enrol: !ref <save_folder>/enrol.csv

embedding_file:
    https://www.dropbox.com/s/skfz2sme5nw7jji/xvector_model.ckpt?dl=1
# classifier_file:
freeze_embeddings: False

# Training hyperparameters
number_of_epochs: 25
batch_size: 128
num_corrupts: 1
lr: 0.00025
lr_final: 0.00005
device: 'cuda:0'

# Feature parameters
n_mels: 24
left_frames: 0
right_frames: 0
deltas: False

out_n_neurons: 1211

# Functions
compute_features: !new:speechbrain.lobes.features.fbank.Fbank
    n_mels: !ref <n_mels>
    left_frames: !ref <left_frames>
    right_frames: !ref <right_frames>
    deltas: !ref <deltas>

embedding_model: !new:speechbrain.lobes.models.Xvector.Xvector
    activation: !name:torch.nn.LeakyReLU
    device: !ref <device>
    tdnn_blocks: 5
    tdnn_channels: [512, 512, 512, 512, 1500]
    tdnn_kernel_sizes: [5, 3, 3, 1, 1]
    tdnn_dilations: [1, 2, 3, 1, 1]
    lin_neurons: 512

classifier: !new:speechbrain.lobes.models.Xvector.Classifier
    activation: !name:torch.nn.LeakyReLU
    device: !ref <device>
    lin_blocks: 1
    lin_neurons: 512
    out_neurons: !ref <out_n_neurons>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

env_corrupt: !new:speechbrain.lobes.augment.env_corrupt.EnvCorrupt
    openrir_source: /miniscratch/voxceleb1/rirs_noises.zip
    openrir_folder: !ref <data_folder>
    openrir_max_noise_len: 3.0  # seconds
    reverb_prob: 1.0
    noise_prob: 1.0
    noise_snr_low: 0
    noise_snr_high: 15
    rir_scale_factor: 1.0

augmentation: !new:speechbrain.lobes.augment.tdsa.TimeDomainSpecAugment
    sample_rate: 16000
    speeds: [100]

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <batch_size>
    csv_read: [wav, spk_id]
    sentence_sorting: random
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <batch_size>
    csv_read: [wav, spk_id]
    sentence_sorting: random
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/

enrol_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_enrol>
    batch_size: 1
    csv_read: [wav]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    batch_size: 1
    csv_read: [wav]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

mean_var_norm_emb: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
    std_norm: False

projection: !new:speechbrain.nnet.losses.Projection
    inp_neurons: 1024
    lin_neurons: 4096
    out_neurons: 1

cont_loss: !new:speechbrain.nnet.losses.BinaryContrastiveLoss
    device: !ref <device>
    projection: !ref <projection>

cont_wrapper: !new:speechbrain.nnet.losses.ContrastiveLearningWrapper
    cont_loss: !ref <cont_loss>
    criterion: !new:torch.nn.BCEWithLogitsLoss
        reduction: "none"
    nl_weight: 1.0

compute_cost: !name:speechbrain.nnet.losses.nll_loss

compute_error: !name:speechbrain.nnet.losses.classification_error

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
    learning_rate: !ref <lr>

lr_annealing: !new:speechbrain.nnet.lr_schedulers.LinearLRScheduler
    lr_initial: !ref <lr>
    lr_final: !ref <lr_final>
    N_epochs: !ref <number_of_epochs>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        embedding_model: !ref <embedding_model>
        classifier: !ref <classifier>
        cont_loss: !ref <cont_loss>
        optimizer: !ref <optimizer>
        normalizer: !ref <mean_var_norm>
        counter: !ref <epoch_counter>
