# ################################
# Model: DCCRN model with complex signal approximation
# Authors: Chien-Feng Liao
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: !PLACEHOLDER  # e.g, 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Basic parameters
data_folder: !PLACEHOLDER
output_folder: !ref results/complexDCCRN_dynamic_mag/<seed>
enhanced_folder: !ref <output_folder>/enhanced/

use_tensorboard: False
tensorboard_logs: !ref results/logs/complexDCCRN_dynamic_mag/<seed>
train_log: !ref <output_folder>/train_log.txt

use_multigpu: True

# Data files
csv_noise: !ref <data_folder>/tr_noise.csv
csv_clean: !ref <data_folder>/tr_clean.csv
csv_valid: !ref <data_folder>/valid.csv
csv_test: !ref <data_folder>/test.csv

# Training Parameters
N_epochs: 50
N_batch: 8
lr: 0.0001
device: cuda

# Model Parameters
conv_channels: [32, 64, 128, 128, 128, 256]
kernel_size: [3, 5]
padding_type: same
strides: [2, 1]
rnn_size: 256
rnn_layers: 2

mask_activation: !new:torch.nn.ReLU

# FFT Parameters
samplerate: 16000
n_fft: 512
win_length: 32
hop_length: 16

add_noise: !new:speechbrain.processing.speech_augmentation.AddNoise
  csv_file: !ref <csv_noise>
  snr_low: 0
  snr_high: 40
  pad_noise: False
  start_index: 0
  csv_read: [wav]

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
  csv_file: !ref <csv_clean>
  batch_size: !ref <N_batch>
  csv_read: [wav]
  cache: False
  num_workers: 1

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
  csv_file: !ref <csv_valid>
  batch_size: !ref <N_batch>
  csv_read: [wav, target]

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
  csv_file: !ref <csv_test>
  batch_size: !ref <N_batch>
  csv_read: [wav, target]

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
  limit: !ref <N_epochs>

compute_stft: !new:speechbrain.processing.features.STFT
  sample_rate: !ref <samplerate>
  win_length: !ref <win_length>
  hop_length: !ref <hop_length>
  n_fft: !ref <n_fft>

compute_istft: !new:speechbrain.processing.features.ISTFT
  sample_rate: !ref <samplerate>
  win_length: !ref <win_length>
  hop_length: !ref <hop_length>

model: !new:speechbrain.lobes.models.DCCRN.DCCRN
  conv_channels: !ref <conv_channels>
  kernel_size: !ref <kernel_size>
  strides: !ref <strides>
  rnn_size: !ref <rnn_size>
  rnn_layers: !ref <rnn_layers>
  padding: !ref <padding_type>

compute_cost: !name:speechbrain.nnet.losses.mse_loss

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
  learning_rate: !ref <lr>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: !ref <output_folder>/save
  recoverables:
    optimizer: !ref <optimizer>
    counter: !ref <epoch_counter>
    model: !ref <model>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: !ref <train_log>
  summary_fns:
    PESQ: !name:speechbrain.utils.train_logger.summarize_average
    STOI: !name:speechbrain.utils.train_logger.summarize_average
