# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/RNN/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Data files
data_folder: !PLACEHOLDER  # e.g. /path/to/librispeech
csv_label: !ref <data_folder>/train-clean-100.csv
csv_train: !ref <data_folder>/train-960.csv
csv_valid: !ref <data_folder>/dev-clean.csv

# Training parameters
number_of_epochs: 20
batch_size: 128
lr: 0.001
device: 'cuda'
multigpu: False

# Model parameters
emb_size: 128
activation: !name:torch.nn.LeakyReLU
dropout: 0.15
rnn_layers: 2
rnn_neurons: 1024
dnn_blocks: 1
dnn_neurons: 512

# Outputs
output_neurons: 29 # 28 chars + 1 eos/bos
bos_index: !ref <output_neurons> - 1
eos_index: !ref <output_neurons> - 1

# Functions
model: !new:speechbrain.lobes.models.RNNLM.RNNLM
    output_neurons: !ref <output_neurons>
    embedding_dim: !ref <emb_size>
    activation: !ref <activation>
    dropout: !ref <dropout>
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
    learning_rate: !ref <lr>

lr_annealing: !new:speechbrain.nnet.lr_schedulers.NewBobLRScheduler
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

label_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_label>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending # This must be the same as the ASR recipe
    output_folder: !ref <output_folder>
    csv_read: [char]

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <batch_size>
    sentence_sorting: random
    output_folder: !ref <output_folder>
    csv_read: [char]

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [char]

compute_cost: !name:speechbrain.nnet.losses.nll_loss

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
    summary_fns:
        loss: !name:speechbrain.utils.train_logger.summarize_average
